"""
GModular — BWM/WOK Integration Tests
=====================================
Tests the BWM V1.0 binary parser and writer against real-format synthetic assets.
Reference implementations: kotorblender io_scene_kotor/format/bwm/reader.py,
PyKotor Libraries/PyKotor/src/pykotor/resource/formats/bwm/io_bwm.py

Test data is generated by tools/gen_test_assets.py and located in tests/test_data/.

Coverage:
 - BWM header parsing (magic, version, bwm_type)
 - Vertex / face loading (count, coordinates, materials)
 - Surface-material walkability mapping
 - Normal vector correctness
 - AABB tree loading
 - Adjacent-edge table loading
 - Round-trip encode/decode (WOKWriter → WOKParser)
 - height_at / face_at / surface_material_at spatial queries
 - bounds / walkable_region_center / material_counts
 - clamp_to_walkmesh / is_position_walkable
 - walk_tris / nowalk_tris
 - build_module_walkmesh aggregation
 - PWK (placeable walkmesh) parsing
 - Error / edge-case robustness
"""
from __future__ import annotations

import math
import os
import struct
import unittest
from pathlib import Path
from typing import List, Tuple

# ── Helpers ───────────────────────────────────────────────────────────────────

TEST_DATA = Path(__file__).parent / "test_data"


def _simple_wok() -> bytes:
    """Return the bytes of test_simple.wok (4-face, 6-vertex)."""
    return (TEST_DATA / "test_simple.wok").read_bytes()


def _grid_wok() -> bytes:
    return (TEST_DATA / "test_grid.wok").read_bytes()


def _terrain_wok() -> bytes:
    return (TEST_DATA / "test_terrain.wok").read_bytes()


def _pwk() -> bytes:
    return (TEST_DATA / "test_placeable.pwk").read_bytes()


def pack_f3(x, y, z):
    return struct.pack("<fff", x, y, z)


def face_normal(v0, v1, v2):
    ax = v1[0] - v0[0]; ay = v1[1] - v0[1]; az = v1[2] - v0[2]
    bx = v2[0] - v0[0]; by = v2[1] - v0[1]; bz = v2[2] - v0[2]
    nx = ay * bz - az * by
    ny = az * bx - ax * bz
    nz = ax * by - ay * bx
    l = math.sqrt(nx * nx + ny * ny + nz * nz)
    return (nx / l, ny / l, nz / l) if l > 1e-9 else (0.0, 0.0, 1.0)


# ── Imports ───────────────────────────────────────────────────────────────────

from gmodular.formats.wok_parser import (
    WOKParser,
    WOKWriter,
    WalkFace,
    WalkMesh,
    AABBNode,
    is_walkable,
    build_module_walkmesh,
    _ray_triangle_intersect,
    _face_normal,
    BWM_MAGIC,
    BWM_VERSION,
    BWM_TYPE_WOK,
    BWM_TYPE_PWK_DWK,
    BWM_HEADER_SIZE,
)


# ═════════════════════════════════════════════════════════════════════════════
#  1. Header / Magic
# ═════════════════════════════════════════════════════════════════════════════

class TestBWMHeader(unittest.TestCase):

    def test_magic_constant(self):
        self.assertEqual(BWM_MAGIC, b"BWM ")

    def test_version_constant(self):
        self.assertEqual(BWM_VERSION, b"V1.0")

    def test_header_size_constant(self):
        self.assertEqual(BWM_HEADER_SIZE, 136)

    def test_bwm_type_wok(self):
        """BWM_TYPE_WOK == 1: area model (AreaModel in BWMType enum)."""
        self.assertEqual(BWM_TYPE_WOK, 1)

    def test_bwm_type_pwk(self):
        """BWM_TYPE_PWK_DWK == 0: placeable/door (PlaceableOrDoor in BWMType enum)."""
        self.assertEqual(BWM_TYPE_PWK_DWK, 0)

    def test_simple_wok_has_correct_magic(self):
        data = _simple_wok()
        self.assertEqual(data[:4], b"BWM ")

    def test_simple_wok_has_correct_version(self):
        data = _simple_wok()
        self.assertEqual(data[4:8], b"V1.0")

    def test_simple_wok_bwm_type_area(self):
        bwm_type, = struct.unpack_from("<I", _simple_wok(), 8)
        self.assertEqual(bwm_type, BWM_TYPE_WOK)

    def test_pwk_bwm_type_placeable(self):
        bwm_type, = struct.unpack_from("<I", _pwk(), 8)
        self.assertEqual(bwm_type, BWM_TYPE_PWK_DWK)

    def test_parse_bad_magic_returns_empty(self):
        bad = b"XXXX" + _simple_wok()[4:]
        wm = WOKParser.from_bytes(bad, name="bad")
        self.assertEqual(wm.face_count, 0)

    def test_parse_bad_version_returns_empty(self):
        bad = _simple_wok()[:4] + b"V9.9" + _simple_wok()[8:]
        wm = WOKParser.from_bytes(bad, name="bad")
        self.assertEqual(wm.face_count, 0)

    def test_parse_too_small_returns_empty(self):
        wm = WOKParser.from_bytes(b"BWM V1.0short", name="short")
        self.assertEqual(wm.face_count, 0)

    def test_parse_empty_bytes_returns_empty(self):
        wm = WOKParser.from_bytes(b"", name="empty")
        self.assertEqual(wm.face_count, 0)


# ═════════════════════════════════════════════════════════════════════════════
#  2. Parsing — Simple WOK (4 faces)
# ═════════════════════════════════════════════════════════════════════════════

class TestSimpleWOKParsing(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_simple_wok(), name="test_simple")

    # --- basic counts ---

    def test_name(self):
        self.assertEqual(self.wm.name, "test_simple")

    def test_total_face_count(self):
        self.assertEqual(self.wm.face_count, 4)

    def test_walkable_face_count(self):
        self.assertEqual(self.wm.walkable_face_count, 2)

    def test_non_walkable_face_count(self):
        self.assertEqual(len(self.wm.non_walkable_faces), 2)

    def test_has_aabb_nodes(self):
        self.assertGreater(len(self.wm.aabbs), 0)

    def test_position_is_origin(self):
        self.assertAlmostEqual(self.wm.position[0], 0.0, places=5)
        self.assertAlmostEqual(self.wm.position[1], 0.0, places=5)
        self.assertAlmostEqual(self.wm.position[2], 0.0, places=5)

    # --- face geometry ---

    def test_faces_are_walkface_instances(self):
        for f in self.wm.faces:
            self.assertIsInstance(f, WalkFace)

    def test_walkable_faces_have_dirt_material(self):
        for f in self.wm.walkable_faces:
            self.assertEqual(f.material, 0)  # Dirt

    def test_nonwalk_faces_have_nonwalk_material(self):
        for f in self.wm.non_walkable_faces:
            self.assertEqual(f.material, 6)  # NonWalk

    def test_face_vertices_are_tuples(self):
        f = self.wm.faces[0]
        self.assertEqual(len(f.v0), 3)
        self.assertEqual(len(f.v1), 3)
        self.assertEqual(len(f.v2), 3)

    def test_face_normal_is_unit_vector(self):
        for f in self.wm.faces:
            n = f.normal
            length = math.sqrt(n[0]**2 + n[1]**2 + n[2]**2)
            self.assertAlmostEqual(length, 1.0, places=5,
                                   msg=f"Normal not unit: {n}")

    def test_face_upward_normals(self):
        """Flat walkmesh faces should have upward-facing normals (nz > 0)."""
        for f in self.wm.faces:
            self.assertGreater(f.normal[2], 0.5,
                               msg=f"Face normal not upward: {f.normal}")

    def test_face_center_within_bounds(self):
        """Each face center must lie within the walkmesh bounding box."""
        bb_min, bb_max = self.wm.bounds()
        for f in self.wm.faces:
            cx, cy, cz = f.center
            self.assertGreaterEqual(cx, bb_min[0] - 0.01)
            self.assertLessEqual(cx, bb_max[0] + 0.01)
            self.assertGreaterEqual(cy, bb_min[1] - 0.01)
            self.assertLessEqual(cy, bb_max[1] + 0.01)

    # --- walkability property ---

    def test_walkface_walkable_property_true(self):
        f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=0)
        self.assertTrue(f.walkable)

    def test_walkface_walkable_property_false(self):
        f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=6)
        self.assertFalse(f.walkable)


# ═════════════════════════════════════════════════════════════════════════════
#  3. Grid WOK parsing (32 faces, mixed materials)
# ═════════════════════════════════════════════════════════════════════════════

class TestGridWOKParsing(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_grid_wok(), name="test_grid")

    def test_face_count(self):
        self.assertEqual(self.wm.face_count, 32)

    def test_has_mixed_materials(self):
        mats = {f.material for f in self.wm.faces}
        self.assertIn(0, mats)   # Dirt
        self.assertIn(6, mats)   # NonWalk
        self.assertTrue(len(mats) > 1, "Expected mixed materials")

    def test_has_walkable_and_nonwalkable(self):
        self.assertGreater(len(self.wm.walkable_faces), 0)
        self.assertGreater(len(self.wm.non_walkable_faces), 0)

    def test_material_counts_sum_to_total(self):
        counts = self.wm.material_counts()
        self.assertEqual(sum(counts.values()), self.wm.face_count)

    def test_bounds_are_reasonable(self):
        bb_min, bb_max = self.wm.bounds()
        self.assertLess(bb_min[0], bb_max[0])
        self.assertLess(bb_min[1], bb_max[1])

    def test_walkable_region_center_is_inside_bounds(self):
        c = self.wm.walkable_region_center()
        self.assertIsNotNone(c)
        bb_min, bb_max = self.wm.bounds()
        self.assertGreaterEqual(c[0], bb_min[0] - 0.1)
        self.assertLessEqual(c[0], bb_max[0] + 0.1)


# ═════════════════════════════════════════════════════════════════════════════
#  4. Terrain WOK (non-flat, 18 faces)
# ═════════════════════════════════════════════════════════════════════════════

class TestTerrainWOKParsing(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_terrain_wok(), name="test_terrain")

    def test_face_count(self):
        self.assertEqual(self.wm.face_count, 18)

    def test_all_stone_material(self):
        for f in self.wm.faces:
            self.assertEqual(f.material, 3)  # Stone

    def test_all_walkable(self):
        self.assertEqual(self.wm.walkable_face_count, 18)

    def test_z_variation(self):
        """Non-flat terrain should have vertex Z values that vary."""
        z_vals = set()
        for f in self.wm.faces:
            for v in (f.v0, f.v1, f.v2):
                z_vals.add(round(v[2], 3))
        self.assertGreater(len(z_vals), 1, "Expected varying Z values for terrain")


# ═════════════════════════════════════════════════════════════════════════════
#  5. PWK (placeable walkmesh)
# ═════════════════════════════════════════════════════════════════════════════

class TestPWKParsing(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_pwk(), name="test_pwk")

    def test_face_count(self):
        self.assertEqual(self.wm.face_count, 1)

    def test_single_walkable_face(self):
        self.assertEqual(self.wm.walkable_face_count, 1)


# ═════════════════════════════════════════════════════════════════════════════
#  6. Spatial Query Methods
# ═════════════════════════════════════════════════════════════════════════════

class TestSpatialQueries(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_simple_wok(), name="spatial")
        # simple.wok walkable area spans (0,0)→(2,2) approx
        # non-walkable spans (2,0)→(4,2)

    def test_height_at_walkable_returns_float(self):
        z = self.wm.height_at(0.5, 0.5)
        self.assertIsNotNone(z)
        self.assertAlmostEqual(z, 0.0, places=4)

    def test_height_at_nonwalk_area_returns_none(self):
        """Query over non-walkable face should return None (walkable_only=True)."""
        z = self.wm.height_at(3.0, 1.0)
        self.assertIsNone(z)

    def test_height_at_any_nonwalk_returns_float(self):
        z = self.wm.height_at_any(3.0, 1.0)
        self.assertIsNotNone(z)
        self.assertAlmostEqual(z, 0.0, places=4)

    def test_height_at_outside_returns_none(self):
        z = self.wm.height_at(100.0, 100.0)
        self.assertIsNone(z)

    def test_face_at_walkable_returns_walkface(self):
        f = self.wm.face_at(0.5, 0.5)
        self.assertIsNotNone(f)
        self.assertIsInstance(f, WalkFace)
        self.assertTrue(f.walkable)

    def test_face_at_nonwalk_returns_none_when_walkable_only(self):
        f = self.wm.face_at(3.0, 1.0, walkable_only=True)
        self.assertIsNone(f)

    def test_face_at_nonwalk_returns_face_when_all(self):
        f = self.wm.face_at(3.0, 1.0, walkable_only=False)
        self.assertIsNotNone(f)
        self.assertFalse(f.walkable)

    def test_surface_material_at_walkable(self):
        mat = self.wm.surface_material_at(0.5, 0.5)
        self.assertEqual(mat, 0)  # Dirt

    def test_surface_material_at_nonwalk(self):
        mat = self.wm.surface_material_at(3.0, 1.0)
        self.assertEqual(mat, 6)  # NonWalk

    def test_surface_material_at_outside(self):
        mat = self.wm.surface_material_at(100.0, 100.0)
        self.assertEqual(mat, -1)

    def test_is_position_walkable_true(self):
        self.assertTrue(self.wm.is_position_walkable(0.5, 0.5))

    def test_is_position_walkable_false_outside(self):
        self.assertFalse(self.wm.is_position_walkable(100.0, 100.0))

    def test_clamp_to_walkmesh_on_walkable(self):
        result = self.wm.clamp_to_walkmesh(0.5, 0.5)
        self.assertIsNotNone(result)
        self.assertAlmostEqual(result[0], 0.5, places=4)
        self.assertAlmostEqual(result[1], 0.5, places=4)

    def test_clamp_to_walkmesh_near_but_off(self):
        """Point just off the walkable area should snap to nearest face center."""
        result = self.wm.clamp_to_walkmesh(0.5, -0.5, search_radius=5.0)
        self.assertIsNotNone(result)

    def test_clamp_to_walkmesh_far_away_returns_none(self):
        result = self.wm.clamp_to_walkmesh(500.0, 500.0, search_radius=0.1)
        self.assertIsNone(result)

    def test_walk_tris_count(self):
        tris = self.wm.walk_tris()
        self.assertEqual(len(tris), 2)

    def test_nowalk_tris_count(self):
        tris = self.wm.nowalk_tris()
        self.assertEqual(len(tris), 2)

    def test_walk_tris_are_tuples_of_3(self):
        for tri in self.wm.walk_tris():
            self.assertEqual(len(tri), 3)


# ═════════════════════════════════════════════════════════════════════════════
#  7. Bounds / Geometry Helpers
# ═════════════════════════════════════════════════════════════════════════════

class TestBoundsHelpers(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_simple_wok(), name="bounds")

    def test_bounds_returns_two_tuples(self):
        result = self.wm.bounds()
        self.assertEqual(len(result), 2)
        bb_min, bb_max = result
        self.assertEqual(len(bb_min), 3)
        self.assertEqual(len(bb_max), 3)

    def test_bounds_min_less_than_max(self):
        bb_min, bb_max = self.wm.bounds()
        for i in range(3):
            self.assertLessEqual(bb_min[i], bb_max[i])

    def test_bounds_covers_expected_area(self):
        bb_min, bb_max = self.wm.bounds()
        self.assertAlmostEqual(bb_min[0], 0.0, places=4)
        self.assertAlmostEqual(bb_min[1], 0.0, places=4)
        self.assertAlmostEqual(bb_max[0], 4.0, places=4)
        self.assertAlmostEqual(bb_max[1], 2.0, places=4)

    def test_bounds_empty_walkmesh(self):
        wm = WalkMesh(name="empty")
        bb_min, bb_max = wm.bounds()
        self.assertEqual(bb_min, (0.0, 0.0, 0.0))
        self.assertEqual(bb_max, (0.0, 0.0, 0.0))

    def test_walkable_region_center_not_none(self):
        c = self.wm.walkable_region_center()
        self.assertIsNotNone(c)

    def test_walkable_region_center_inside_bounds(self):
        c = self.wm.walkable_region_center()
        bb_min, bb_max = self.wm.bounds()
        self.assertGreaterEqual(c[0], bb_min[0] - 0.01)
        self.assertLessEqual(c[0], bb_max[0] + 0.01)
        self.assertGreaterEqual(c[1], bb_min[1] - 0.01)
        self.assertLessEqual(c[1], bb_max[1] + 0.01)

    def test_walkable_region_center_none_on_empty(self):
        wm = WalkMesh(name="e")
        self.assertIsNone(wm.walkable_region_center())

    def test_material_counts_correct(self):
        mc = self.wm.material_counts()
        self.assertEqual(mc.get(0, 0), 2)   # 2 Dirt faces
        self.assertEqual(mc.get(6, 0), 2)   # 2 NonWalk faces

    def test_face_center_property(self):
        f = WalkFace(v0=(0,0,0), v1=(2,0,0), v2=(1,2,0), material=0)
        cx, cy, cz = f.center
        self.assertAlmostEqual(cx, 1.0, places=5)
        self.assertAlmostEqual(cy, 2/3, places=5)
        self.assertAlmostEqual(cz, 0.0, places=5)


# ═════════════════════════════════════════════════════════════════════════════
#  8. Surface Material Walkability
# ═════════════════════════════════════════════════════════════════════════════

class TestSurfaceMaterial(unittest.TestCase):

    WALKABLE = [0, 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 17, 18, 19]
    NOT_WALKABLE = [6, 7, 14, 15, 16]

    def test_all_known_walkable(self):
        for mat in self.WALKABLE:
            self.assertTrue(is_walkable(mat), f"Material {mat} should be walkable")

    def test_all_known_nonwalkable(self):
        for mat in self.NOT_WALKABLE:
            self.assertFalse(is_walkable(mat), f"Material {mat} should not be walkable")

    def test_out_of_range_not_walkable(self):
        self.assertFalse(is_walkable(100))
        self.assertFalse(is_walkable(-1))

    def test_door_material_walkable(self):
        self.assertTrue(is_walkable(17))  # Door = walkable

    def test_lava_not_walkable(self):
        self.assertFalse(is_walkable(14))

    def test_bottomless_pit_not_walkable(self):
        self.assertFalse(is_walkable(15))

    def test_deepwater_not_walkable(self):
        self.assertFalse(is_walkable(16))

    def test_dirt_walkable(self):
        self.assertTrue(is_walkable(0))

    def test_stone_walkable(self):
        self.assertTrue(is_walkable(3))


# ═════════════════════════════════════════════════════════════════════════════
#  9. AABB Node Parsing
# ═════════════════════════════════════════════════════════════════════════════

class TestAABBParsing(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_simple_wok())

    def test_has_at_least_one_aabb(self):
        self.assertGreater(len(self.wm.aabbs), 0)

    def test_aabb_nodes_are_aabbnode_instances(self):
        for n in self.wm.aabbs:
            self.assertIsInstance(n, AABBNode)

    def test_aabb_bb_min_has_3_components(self):
        n = self.wm.aabbs[0]
        self.assertEqual(len(n.bb_min), 3)

    def test_aabb_bb_max_has_3_components(self):
        n = self.wm.aabbs[0]
        self.assertEqual(len(n.bb_max), 3)

    def test_aabb_bounds_ordered(self):
        n = self.wm.aabbs[0]
        for i in range(3):
            self.assertLessEqual(n.bb_min[i], n.bb_max[i],
                                 msg=f"AABB min[{i}] > max[{i}]")

    def test_root_aabb_covers_walkmesh(self):
        """Root AABB should cover the entire walkmesh geometry."""
        wm_min, wm_max = self.wm.bounds()
        n = self.wm.aabbs[0]
        for i in range(3):
            self.assertLessEqual(n.bb_min[i], wm_min[i] + 0.2,
                                 msg=f"AABB min[{i}] too large")
            self.assertGreaterEqual(n.bb_max[i], wm_max[i] - 0.2,
                                    msg=f"AABB max[{i}] too small")


# ═════════════════════════════════════════════════════════════════════════════
#  10. Adjacent-Edge Table
# ═════════════════════════════════════════════════════════════════════════════

class TestAdjEdges(unittest.TestCase):

    def setUp(self):
        self.wm = WOKParser.from_bytes(_simple_wok())

    def test_adj_edges_count_equals_walkable_faces(self):
        """Adjacent-edge table has one row per walkable face."""
        self.assertEqual(len(self.wm.adj_edges), self.wm.walkable_face_count)

    def test_adj_edges_are_3tuples(self):
        for row in self.wm.adj_edges:
            self.assertEqual(len(row), 3)

    def test_adj_edges_all_minus_one_or_valid(self):
        """Each adj edge is -1 (no neighbor) or a non-negative face index."""
        n_faces = self.wm.walkable_face_count
        for row in self.wm.adj_edges:
            for val in row:
                self.assertTrue(val == -1 or val >= 0,
                                msg=f"Invalid adj edge: {val}")


# ═════════════════════════════════════════════════════════════════════════════
#  11. Round-Trip (WOKWriter → WOKParser)
# ═════════════════════════════════════════════════════════════════════════════

class TestBWMRoundTrip(unittest.TestCase):

    def _round_trip(self, wm: WalkMesh) -> WalkMesh:
        data = WOKWriter(wm).to_bytes()
        return WOKParser.from_bytes(data, name=wm.name + "_rt")

    def test_simple_round_trip_face_count(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        rt = self._round_trip(wm)
        self.assertEqual(rt.face_count, wm.face_count)

    def test_simple_round_trip_walkable_count(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        rt = self._round_trip(wm)
        self.assertEqual(rt.walkable_face_count, wm.walkable_face_count)

    def test_simple_round_trip_materials(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        rt = self._round_trip(wm)
        orig_mats = sorted(f.material for f in wm.faces)
        rt_mats   = sorted(f.material for f in rt.faces)
        self.assertEqual(orig_mats, rt_mats)

    def test_simple_round_trip_has_aabbs(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        rt = self._round_trip(wm)
        self.assertGreater(len(rt.aabbs), 0)

    def test_grid_round_trip_face_count(self):
        wm = WOKParser.from_bytes(_grid_wok(), name="rt_grid")
        rt = self._round_trip(wm)
        self.assertEqual(rt.face_count, wm.face_count)

    def test_grid_round_trip_material_counts(self):
        wm = WOKParser.from_bytes(_grid_wok(), name="rt_grid")
        rt = self._round_trip(wm)
        self.assertEqual(wm.material_counts(), rt.material_counts())

    def test_grid_round_trip_walkable_count(self):
        wm = WOKParser.from_bytes(_grid_wok(), name="rt_grid")
        rt = self._round_trip(wm)
        self.assertEqual(wm.walkable_face_count, rt.walkable_face_count)

    def test_terrain_round_trip_face_count(self):
        wm = WOKParser.from_bytes(_terrain_wok(), name="rt_terrain")
        rt = self._round_trip(wm)
        self.assertEqual(rt.face_count, wm.face_count)

    def test_round_trip_normals_unit(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        rt = self._round_trip(wm)
        for f in rt.faces:
            n = f.normal
            length = math.sqrt(n[0]**2 + n[1]**2 + n[2]**2)
            self.assertAlmostEqual(length, 1.0, places=4)

    def test_round_trip_spatial_query_height(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        orig_z = wm.height_at(0.5, 0.5)
        rt = self._round_trip(wm)
        rt_z = rt.height_at(0.5, 0.5)
        self.assertIsNotNone(rt_z)
        self.assertAlmostEqual(orig_z, rt_z, places=4)

    def test_round_trip_bounds_match(self):
        wm = WOKParser.from_bytes(_simple_wok(), name="rt_simple")
        orig_bounds = wm.bounds()
        rt = self._round_trip(wm)
        rt_bounds = rt.bounds()
        for i in range(3):
            self.assertAlmostEqual(orig_bounds[0][i], rt_bounds[0][i], places=3)
            self.assertAlmostEqual(orig_bounds[1][i], rt_bounds[1][i], places=3)

    def test_manual_walkmesh_round_trip(self):
        """Build a WalkMesh manually, write it, read it back."""
        wm = WalkMesh(name="manual")
        wm.faces = [
            WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=0,
                     normal=(0,0,1)),
            WalkFace(v0=(1,0,0), v1=(1,1,0), v2=(0,1,0), material=3,
                     normal=(0,0,1)),
            WalkFace(v0=(2,0,0), v1=(3,0,0), v2=(2,1,0), material=6,
                     normal=(0,0,1)),
        ]
        rt = self._round_trip(wm)
        self.assertEqual(rt.face_count, 3)
        self.assertEqual(rt.walkable_face_count, 2)
        self.assertEqual(sorted(f.material for f in rt.faces),
                         sorted(f.material for f in wm.faces))

    def test_writer_produces_valid_bwm_header(self):
        """WOKWriter output must start with BWM  V1.0."""
        wm = WalkMesh(name="hdr_test")
        wm.faces = [WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0),
                             material=0, normal=(0,0,1))]
        data = WOKWriter(wm).to_bytes()
        self.assertEqual(data[:4], b"BWM ")
        self.assertEqual(data[4:8], b"V1.0")

    def test_writer_output_size_minimum(self):
        """WOKWriter output must be at least HEADER_SIZE bytes."""
        wm = WalkMesh(name="size_test")
        wm.faces = [WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0),
                             material=0, normal=(0,0,1))]
        data = WOKWriter(wm).to_bytes()
        self.assertGreaterEqual(len(data), BWM_HEADER_SIZE)

    def test_writer_empty_walkmesh_produces_valid_binary(self):
        """Even an empty walkmesh should produce a parseable BWM binary."""
        wm = WalkMesh(name="empty")
        data = WOKWriter(wm).to_bytes()
        self.assertEqual(data[:4], b"BWM ")
        rt = WOKParser.from_bytes(data, name="empty_rt")
        self.assertEqual(rt.face_count, 0)


# ═════════════════════════════════════════════════════════════════════════════
#  12. Module Walkmesh Aggregation
# ═════════════════════════════════════════════════════════════════════════════

class TestBuildModuleWalkmesh(unittest.TestCase):

    def test_empty_placements_returns_empty(self):
        wm = build_module_walkmesh([])
        self.assertEqual(wm.face_count, 0)

    def test_single_room_from_filesystem(self):
        """Load one room WOK from the test_data directory."""
        class FakePlacement:
            resref = "test_simple"
            position = (0.0, 0.0, 0.0)

        wm = build_module_walkmesh(
            [FakePlacement()],
            game_dir=str(TEST_DATA)
        )
        self.assertEqual(wm.face_count, 4)

    def test_two_rooms_offset(self):
        """Two rooms side-by-side should double the face count."""
        class P1:
            resref = "test_simple"
            position = (0.0, 0.0, 0.0)
        class P2:
            resref = "test_simple"
            position = (10.0, 0.0, 0.0)

        wm = build_module_walkmesh([P1(), P2()], game_dir=str(TEST_DATA))
        self.assertEqual(wm.face_count, 8)

    def test_world_offset_applied(self):
        """Faces from a room at (10,0,0) should have X ≥ 10."""
        class P:
            resref = "test_simple"
            position = (10.0, 0.0, 0.0)

        wm = build_module_walkmesh([P()], game_dir=str(TEST_DATA))
        for face in wm.faces:
            for v in (face.v0, face.v1, face.v2):
                self.assertGreaterEqual(v[0], 10.0 - 0.01,
                                        msg=f"Vertex not offset: {v}")

    def test_missing_room_skipped_gracefully(self):
        """Missing WOK files should be skipped without error."""
        class P:
            resref = "does_not_exist_anywhere_xyz"
            position = (0.0, 0.0, 0.0)

        wm = build_module_walkmesh([P()], game_dir=str(TEST_DATA))
        self.assertEqual(wm.face_count, 0)

    def test_module_walkmesh_name(self):
        wm = build_module_walkmesh([])
        self.assertEqual(wm.name, "module")


# ═════════════════════════════════════════════════════════════════════════════
#  13. Math Helpers
# ═════════════════════════════════════════════════════════════════════════════

class TestMathHelpers(unittest.TestCase):

    def test_face_normal_upward_flat_triangle(self):
        n = _face_normal((0,0,0), (1,0,0), (0,1,0))
        self.assertAlmostEqual(n[2], 1.0, places=5)

    def test_face_normal_unit_length(self):
        n = _face_normal((0,0,0), (3,0,0), (0,4,0))
        l = math.sqrt(n[0]**2 + n[1]**2 + n[2]**2)
        self.assertAlmostEqual(l, 1.0, places=5)

    def test_face_normal_degenerate_returns_fallback(self):
        # Degenerate triangle (all same point)
        n = _face_normal((1,1,1), (1,1,1), (1,1,1))
        self.assertEqual(len(n), 3)
        # Should not raise; result is some unit-ish vector

    def test_ray_triangle_hit(self):
        """Ray straight down hitting a flat triangle at z=0."""
        z = _ray_triangle_intersect(
            (0.5, 0.5, 10.0), (0.0, 0.0, -1.0),
            (0,0,0), (1,0,0), (0,1,0)
        )
        self.assertIsNotNone(z)
        self.assertAlmostEqual(z, 0.0, places=4)

    def test_ray_triangle_miss(self):
        z = _ray_triangle_intersect(
            (5.0, 5.0, 10.0), (0.0, 0.0, -1.0),
            (0,0,0), (1,0,0), (0,1,0)
        )
        self.assertIsNone(z)

    def test_ray_triangle_parallel(self):
        """Ray parallel to the triangle plane should return None."""
        z = _ray_triangle_intersect(
            (0.5, 0.0, 0.5), (1.0, 0.0, 0.0),  # horizontal ray
            (0,0,0), (1,0,0), (0,1,0)
        )
        self.assertIsNone(z)

    def test_ray_triangle_upward_ray_blocked(self):
        """Ray going upward (positive Z) from below the triangle should miss."""
        z = _ray_triangle_intersect(
            (0.5, 0.5, 5.0), (0.0, 0.0, 1.0),  # ray going up, away from triangle
            (0,0,0), (1,0,0), (0,1,0)
        )
        self.assertIsNone(z)

    def test_ray_triangle_elevated_triangle(self):
        """Ray hitting an elevated triangle (z=2)."""
        v0 = (0.0, 0.0, 2.0)
        v1 = (1.0, 0.0, 2.0)
        v2 = (0.0, 1.0, 2.0)
        z = _ray_triangle_intersect(
            (0.25, 0.25, 10.0), (0.0, 0.0, -1.0),
            v0, v1, v2
        )
        self.assertIsNotNone(z)
        self.assertAlmostEqual(z, 2.0, places=4)


# ═════════════════════════════════════════════════════════════════════════════
#  14. WalkFace Data Integrity
# ═════════════════════════════════════════════════════════════════════════════

class TestWalkFaceIntegrity(unittest.TestCase):

    def test_as_tuple_returns_3_verts(self):
        f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=0)
        t = f.as_tuple()
        self.assertEqual(len(t), 3)
        self.assertEqual(t[0], (0,0,0))
        self.assertEqual(t[1], (1,0,0))
        self.assertEqual(t[2], (0,1,0))

    def test_default_normal(self):
        f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=0)
        self.assertEqual(f.normal, (0.0, 0.0, 1.0))

    def test_default_material_zero(self):
        f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0))
        self.assertEqual(f.material, 0)

    def test_all_non_walkable_materials(self):
        for mat in [6, 7, 14, 15, 16]:
            f = WalkFace(v0=(0,0,0), v1=(1,0,0), v2=(0,1,0), material=mat)
            self.assertFalse(f.walkable, msg=f"Material {mat} should not be walkable")

    def test_walkmesh_add_faces(self):
        wm = WalkMesh(name="add_test")
        for i in range(5):
            wm.faces.append(WalkFace(
                v0=(i,0,0), v1=(i+1,0,0), v2=(i,1,0), material=i % 7
            ))
        self.assertEqual(wm.face_count, 5)


# ═════════════════════════════════════════════════════════════════════════════
#  15. From-File Loading
# ═════════════════════════════════════════════════════════════════════════════

class TestFromFile(unittest.TestCase):

    def test_from_file_simple(self):
        path = str(TEST_DATA / "test_simple.wok")
        wm = WOKParser.from_file(path)
        self.assertEqual(wm.face_count, 4)

    def test_from_file_name_from_stem(self):
        path = str(TEST_DATA / "test_simple.wok")
        wm = WOKParser.from_file(path)
        self.assertEqual(wm.name, "test_simple")

    def test_from_file_nonexistent_returns_empty(self):
        wm = WOKParser.from_file("/no/such/file.wok")
        self.assertEqual(wm.face_count, 0)

    def test_from_file_terrain(self):
        path = str(TEST_DATA / "test_terrain.wok")
        wm = WOKParser.from_file(path)
        self.assertEqual(wm.face_count, 18)


# ═════════════════════════════════════════════════════════════════════════════
#  16. Writer — to_file
# ═════════════════════════════════════════════════════════════════════════════

class TestWOKWriterToFile(unittest.TestCase):

    def setUp(self):
        self.tmp = str(TEST_DATA / "tmp_output.wok")

    def tearDown(self):
        if os.path.exists(self.tmp):
            os.unlink(self.tmp)

    def test_to_file_creates_file(self):
        wm = WOKParser.from_bytes(_simple_wok())
        WOKWriter(wm).to_file(self.tmp)
        self.assertTrue(os.path.exists(self.tmp))

    def test_to_file_parseable(self):
        wm = WOKParser.from_bytes(_simple_wok())
        WOKWriter(wm).to_file(self.tmp)
        rt = WOKParser.from_file(self.tmp)
        self.assertEqual(rt.face_count, wm.face_count)


# ═════════════════════════════════════════════════════════════════════════════
#  17. GFF + WOK Integration (module-level)
# ═════════════════════════════════════════════════════════════════════════════

class TestGFFWOKIntegration(unittest.TestCase):
    """Test that walkmesh data integrates correctly with GFF loading."""

    def test_gff_gitplaceable_position(self):
        """GFF GIT placeables have a Position field that maps to WOK coords."""
        from gmodular.formats.gff_types import GITPlaceable, Vector3
        p = GITPlaceable(
            template_resref="test",
            resref="test001",
            tag="MYTAG",
            position=Vector3(1.0, 2.0, 0.0),
            bearing=0.0,
        )
        self.assertAlmostEqual(p.position.x, 1.0, places=5)
        self.assertAlmostEqual(p.position.y, 2.0, places=5)

    def test_walkmesh_at_git_placeable_position(self):
        """height_at() should work at a placeable's XY position."""
        wm = WOKParser.from_bytes(_simple_wok())
        z = wm.height_at(0.5, 0.5)
        self.assertIsNotNone(z)

    def test_module_walkmesh_contains_all_faces(self):
        """Combined walkmesh from 2 rooms has 2x the faces of one room."""
        class R1:
            resref = "test_grid"
            position = (0.0, 0.0, 0.0)
        class R2:
            resref = "test_terrain"
            position = (20.0, 0.0, 0.0)

        wm = build_module_walkmesh([R1(), R2()], game_dir=str(TEST_DATA))
        self.assertEqual(wm.face_count, 32 + 18)


# ═════════════════════════════════════════════════════════════════════════════
#  18. ERF + WOK Packaging
# ═════════════════════════════════════════════════════════════════════════════

class TestERFWOKPackaging(unittest.TestCase):
    """Test packing WOK data into an ERF archive and reading it back."""

    def test_wok_in_erf_round_trip(self):
        """Pack a WOK into an ERF, unpack and re-parse it."""
        from gmodular.formats.archives import ERFWriter, ERFReaderMem

        wm = WOKParser.from_bytes(_simple_wok(), name="packed")
        wok_bytes = WOKWriter(wm).to_bytes()

        # Pack into ERF
        writer = ERFWriter()
        writer.add_resource("packed", "wok", wok_bytes)
        erf_bytes = writer.to_bytes()
        self.assertGreater(len(erf_bytes), 0)

        # Unpack
        reader = ERFReaderMem(erf_bytes)
        result = reader.get_resource("packed", "wok")
        self.assertIsNotNone(result)

        # Re-parse
        rt = WOKParser.from_bytes(result, name="packed_rt")
        self.assertEqual(rt.face_count, wm.face_count)
        self.assertEqual(rt.walkable_face_count, wm.walkable_face_count)

    def test_multiple_woks_in_erf(self):
        """Multiple room WOKs can be stored in one ERF."""
        from gmodular.formats.archives import ERFWriter, ERFReaderMem

        wm1 = WOKParser.from_bytes(_simple_wok(), name="room1")
        wm2 = WOKParser.from_bytes(_grid_wok(),   name="room2")

        writer = ERFWriter()
        writer.add_resource("room1", "wok", WOKWriter(wm1).to_bytes())
        writer.add_resource("room2", "wok", WOKWriter(wm2).to_bytes())
        erf_bytes = writer.to_bytes()

        reader = ERFReaderMem(erf_bytes)
        r1 = WOKParser.from_bytes(reader.get_resource("room1", "wok"), name="r1")
        r2 = WOKParser.from_bytes(reader.get_resource("room2", "wok"), name="r2")

        self.assertEqual(r1.face_count, 4)
        self.assertEqual(r2.face_count, 32)


if __name__ == "__main__":
    unittest.main(verbosity=2)
